set(BULLET_INSTALL_DIR ${CMAKE_CURRENT_BINARY_DIR}/install/bullet)
set(BULLET_INCLUDE_DIR ${BULLET_INSTALL_DIR}/include)
set(BULLET_LIB_DIR ${BULLET_INSTALL_DIR}/lib)

set(BULLET_CMAKE_FLAGS 
	-DBUILD_BULLET2_DEMOS=OFF
	-DBUILD_CPU_DEMOS=OFF
	-DBUILD_EXTRAS=OFF
	-DBUILD_OPENGL3_DEMOS=OFF
	-DBUILD_UNIT_TESTS=OFF
	
	-DINSTALL_LIBS=ON
	-DCMAKE_DEBUG_POSTFIX=
	-DUSE_MSVC_RUNTIME_LIBRARY_DLL=ON
)

ExternalProject_Add(bullet
  DOWNLOAD_COMMAND 	""
  SOURCE_DIR 		${CMAKE_SOURCE_DIR}/Glitter/Vendor/bullet
  CMAKE_ARGS		-DCMAKE_INSTALL_PREFIX:PATH=${BULLET_INSTALL_DIR} ${BULLET_CMAKE_FLAGS}
)

include_directories(${BULLET_INCLUDE_DIR}/bullet)

target_link_libraries(Glitter
 	${BULLET_LIB_DIR}/BulletDynamics${CMAKE_STATIC_LIBRARY_SUFFIX}
 	${BULLET_LIB_DIR}/BulletCollision${CMAKE_STATIC_LIBRARY_SUFFIX}
 	${BULLET_LIB_DIR}/LinearMath${CMAKE_STATIC_LIBRARY_SUFFIX})

add_dependencies(Glitter bullet)
